import img1 from '~/public/unisex-shoe1.jpeg';
import img2 from '~/public/13 Designer Backpacks That Are Worth the Splurge.jpeg';
import img3 from '~/public/15mm Wide Top Flat Square Signet Unisex Ring.jpeg';
import img4 from '~/public/20 Affordable Accessories That Make My T-Shirts Look Expensive.jpeg';
import img5 from '~/public/2fba0c88-e526-4708-8492-47a9ac87b49f.jpeg';
import img6 from '~/public/A Peanut brown, front flap,interwoven buckle, 3_4 sleeve African senator kaftan native_.jpeg';
import img7 from '~/public/Ace Dex Avsmalnande Cargobyxor.jpeg';
import img8 from '~/public/BLACK DARTED HIGH WAIST TROUSERS - MEDIUM.jpeg';
import img9 from '~/public/BLACK HAREM JOGGERS - XL _ black.jpeg';
import img10 from '~/public/BOJOD Rectangle Sunglasses for Women Retro Fashion Sunglasses UV 400 Protection Square Frame Eyewear.jpeg';
import img11 from '~/public/Black ring necklace Jewelry for Men - 22.jpeg';
import img12 from "~/public/Cartier Panthere 18K Yellow Gold Women's Diamond Watch 27mm 1_20ct.jpeg";
import img13 from '~/public/Chanel bracelet.jpeg';
import img14 from '~/public/Denim Basic Ripped Jeans  US$30_00.jpeg';
import img15 from '~/public/EPSOOG YPY Color Contrast T-Shirt - Sky Blue _ XXL.jpeg';
import img16 from '~/public/Elastic Man Suits Pantalon Stretch Pantum For Men Ice Silk Slim Fit refroidissement Tressed Classic Nouveau en été 2024 Slacks Up Luxury.jpeg';
import img17 from '~/public/Elegant Simple Pearl Geometric Necklace Small Pearl.jpeg';
import img18 from '~/public/Ensemble de bracelets chaîne en acier inoxydable - Doré.jpeg';
import img19 from '~/public/Ensemble de sport décontracté à manches courtes pour hommes, ensemble deux pièces, t-shirt et pantalon, vêtements pour hommes, mode été - Blue _ XL.jpeg';
import img20 from '~/public/Fashionable and Popular Men Star Decor Round Charm Layered Necklace Stainless Steel for Jewelry Gift and for a Stylish Look.jpeg';
import img21 from '~/public/Fey Stainless Steel Hinged Hoop Earrings - Style E_Silver _ One Size.jpeg';
import img22 from '~/public/Flap Pocket Side Cargo Pants.jpeg';
import img23 from '~/public/Hand Made Men’s Bead Bracelet Set Of Two Black And White _ Color_ Black_White _ Size_ 7_48 Inches.jpeg';
import img24 from '~/public/Hombres.jpeg';
import img25 from '~/public/JLo.jpeg';
import img26 from '~/public/Jade Accessories wristband.jpeg';
import img27 from '~/public/Jennings.jpeg';
import img28 from '~/public/King Ring.jpeg';
import img29 from '~/public/Ladies Rolex.jpeg';
import img30 from '~/public/Loose Corduroy Shirt - Light Blue _ XL.jpeg';
import img31 from '~/public/Matte Black Stainless Steel Ring.jpeg';
import img32 from "~/public/Meghan Markle Made These Bags So Popular, They Just Won't Stay in Stock.jpeg";
import img33 from '~/public/Men Cross Charm Necklace.jpeg';
import img34 from '~/public/Men Drawstring Waist Straight Leg Trousers.jpeg';
import img35 from '~/public/Men Expression Print Colourblock Drawstring Hooded Tee.jpeg';
import img36 from "~/public/Men's Classic Gothic Steampunk Sunglasses Polarized Brand Designer Vintage Round Metal Frame UV400 Eyewear High Quality.jpeg";
import img37 from "~/public/Men's Jersey Short Sweater Fabric Casual Cutton Drawstring Walk Shorts - XL _ Black.jpeg";
import img38 from "~/public/Men's Printed Simple Round Neck Short Sleeve T-shirt.jpeg";
import img39 from '~/public/Metal Ring Tassel Earrings.jpeg';
import img40 from '~/public/Modern Wrap Ring.jpeg';
import img41 from '~/public/Monica Vinader Doina Chain Necklace, Gold.jpeg';
import img42 from '~/public/NEW DAINTY CRYSTAL CUBAN LINK NECKLACE.jpeg';
import img43 from '~/public/Natural Matte Onyx Bead Hematite Arrow Tiger Eye Stone Energy Bracelet Men Women.jpeg';
import img44 from '~/public/Natural Volcanic Stone Bracelet Men Matte Black Lave White Beads Charm Dumbbell Strand Bracelets Women Barbell Fitness Jewelry, Black Lava Black.jpeg';
import img45 from '~/public/Pantalones de traje casuales y holgados en negro para hombres con pierna recta, pliegues y bolsillo inclinado para el trabajo diario.jpeg';
import img46 from '~/public/Ribbed Knit Flare Leg Trousers.jpeg';
import img47 from '~/public/Sekonda Ladies Pink Dial Silver Watch.jpeg';
import img48 from "~/public/Style Icons_ 5 Women We're Taking Major Fashion Inspo From Right Now.jpeg";
import img49 from '~/public/The Best Designer Inspired Finds - Dancing Mama Style.jpeg';
import img50 from '~/public/Washed Vintage oversized Tees colorful oversized t-shirts - grey _ M.jpeg';

import box from '~/public/box.png';
import truck from '~/public/delivery-truck.png';
import shield from '~/public/shield.png';
import clock from '~/public/24-hours.png';

export const benefits = [
  {
    img: box,
    title: 'Discount',
    description: 'Every week now on sale',
  },
  {
    img: truck,
    title: 'Free Delivery',
    description: '100% Free for all orders',
  },
  {
    img: clock,
    title: 'Great Support 24/7',
    description: 'Support always available',
  },
  {
    img: shield,
    title: 'Secure Payment',
    description: '100% Secure Payment Method',
  },
];

export const products = [
  {
    id: 1,
    name: 'Ring Necklace for Men',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 150,
    category: 'electronics',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 15,
    releaseDate: '2023-07-01',
    img: img1,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 2,
    name: 'Smartphone X12',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 900,
    category: 'electronics',
    isFeatured: true,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-09-20',
    img: img2,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 3,
    name: 'Leather Jacket',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 250,
    category: 'fashion',
    isFeatured: true,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-02-11',
    img: img3,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 4,
    name: 'Fitness Tracker',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 75,
    category: 'fitness',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 20,
    releaseDate: '2023-05-15',
    img: img4,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 5,
    name: '4K Smart TV',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 1200,
    category: 'electronics',
    isFeatured: true,
    isNew: true,
    isDiscounted: false,
    isBestSeller: false,
    discountPercentage: 0,
    releaseDate: '2024-08-01',
    img: img5,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 6,
    name: 'Running Shoes',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 100,
    category: 'fashion',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 10,
    releaseDate: '2023-03-05',
    img: img6,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 7,
    name: 'Gaming Laptop',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 2000,
    category: 'electronics',
    isFeatured: false,
    isNew: true,
    isDiscounted: false,
    isBestSeller: false,
    discountPercentage: 0,
    releaseDate: '2024-07-12',
    img: img7,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 8,
    name: 'Bluetooth Speaker',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 60,
    category: 'electronics',
    isFeatured: false,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 25,
    releaseDate: '2023-10-15',
    img: img8,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 9,
    name: 'Digital Camera',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 800,
    category: 'electronics',
    isFeatured: true,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-01-05',
    img: img9,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 10,
    name: 'Luxury Watch',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 500,
    category: 'fashion',
    isFeatured: false,
    isNew: false,
    isDiscounted: true,
    isBestSeller: false,
    discountPercentage: 30,
    releaseDate: '2022-12-10',
    img: img10,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 11,
    name: 'Electric Scooter',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 350,
    category: 'mobility',
    isFeatured: false,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-08-15',
    img: img11,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 12,
    name: 'Coffee Maker',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 80,
    category: 'home',
    isFeatured: false,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 15,
    releaseDate: '2023-04-25',
    img: img12,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 13,
    name: 'Smart Thermostat',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 150,
    category: 'home',
    isFeatured: true,
    isNew: true,
    isDiscounted: false,
    isBestSeller: false,
    discountPercentage: 0,
    releaseDate: '2024-06-01',
    img: img13,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 14,
    name: 'Electric Guitar',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 700,
    category: 'music',
    isFeatured: true,
    isNew: true,
    isDiscounted: false,
    isBestSeller: false,
    discountPercentage: 0,
    releaseDate: '2024-02-20',
    img: img14,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 15,
    name: 'Backpack',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 60,
    category: 'fashion',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 10,
    releaseDate: '2023-07-05',
    img: img15,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 16,
    name: 'Tablet Pro',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 800,
    category: 'electronics',
    isFeatured: true,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-03-01',
    img: img16,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 17,
    name: 'Robot Vacuum',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 300,
    category: 'home',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 20,
    releaseDate: '2023-06-10',
    img: img17,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 18,
    name: 'Air Purifier',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 200,
    category: 'home',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 25,
    releaseDate: '2023-08-22',
    img: img18,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 19,
    name: 'Gaming Chair',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 180,
    category: 'furniture',
    isFeatured: false,
    isNew: true,
    isDiscounted: false,
    isBestSeller: false,
    discountPercentage: 0,
    releaseDate: '2024-07-10',
    img: img19,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 20,
    name: 'Electric Toothbrush',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 40,
    category: 'personal care',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 15,
    releaseDate: '2023-11-05',
    img: img20,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 21,
    name: 'Air Fryer',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 100,
    category: 'home',
    isFeatured: true,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-01-15',
    img: img21,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 22,
    name: 'Water Bottle',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 25,
    category: 'outdoor',
    isFeatured: false,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-08-12',
    img: img22,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 23,
    name: 'Noise-Cancelling Earbuds',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 120,
    category: 'electronics',
    isFeatured: true,
    isNew: true,
    isDiscounted: false,
    isBestSeller: false,
    discountPercentage: 0,
    releaseDate: '2024-04-01',
    img: img23,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 24,
    name: 'Portable Charger',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 30,
    category: 'electronics',
    isFeatured: false,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-09-10',
    img: img24,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 25,
    name: 'Yoga Mat',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 35,
    category: 'fitness',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 20,
    releaseDate: '2023-02-15',
    img: img25,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 26,
    name: 'Smart Home Security Camera',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 70,
    category: 'home',
    isFeatured: false,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-05-20',
    img: img26,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 27,
    name: 'Digital Photo Frame',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 150,
    category: 'home',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: false,
    discountPercentage: 10,
    releaseDate: '2023-03-11',
    img: img27,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 28,
    name: 'Camping Tent',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 120,
    category: 'outdoor',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: false,
    discountPercentage: 25,
    releaseDate: '2023-07-19',
    img: img28,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 29,
    name: 'VR Headset',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 400,
    category: 'electronics',
    isFeatured: false,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-06-14',
    img: img29,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 30,
    name: 'Cordless Drill',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 100,
    category: 'tools',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 15,
    releaseDate: '2023-09-03',
    img: img30,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 31,
    name: 'Wireless Mouse',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 25,
    category: 'electronics',
    isFeatured: true,
    isNew: true,
    isDiscounted: false,
    isBestSeller: false,
    discountPercentage: 0,
    releaseDate: '2024-09-05',
    img: img31,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 32,
    name: 'Office Chair',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 150,
    category: 'furniture',
    isFeatured: false,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 20,
    releaseDate: '2022-11-17',
    img: img32,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 33,
    name: 'Instant Camera',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 100,
    category: 'electronics',
    isFeatured: false,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-08-20',
    img: img33,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 34,
    name: 'Espresso Machine',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 250,
    category: 'home',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 20,
    releaseDate: '2023-12-01',
    img: img34,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 35,
    name: 'Bluetooth Keyboard',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 60,
    category: 'electronics',
    isFeatured: false,
    isNew: true,
    isDiscounted: false,
    isBestSeller: false,
    discountPercentage: 0,
    releaseDate: '2024-06-25',
    img: img35,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 36,
    name: 'Adjustable Dumbbells',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 400,
    category: 'fitness',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 30,
    releaseDate: '2023-04-09',
    img: img36,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 37,
    name: 'Graphic Tablet',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 200,
    category: 'electronics',
    isFeatured: false,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-07-15',
    img: img37,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 38,
    name: 'Electric Kettle',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 30,
    category: 'home',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 15,
    releaseDate: '2023-02-01',
    img: img38,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 39,
    name: 'Portable Air Conditioner',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 300,
    category: 'home',
    isFeatured: true,
    isNew: true,
    isDiscounted: false,
    isBestSeller: false,
    discountPercentage: 0,
    releaseDate: '2024-06-05',
    img: img39,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 40,
    name: 'Foam Roller',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 25,
    category: 'fitness',
    isFeatured: false,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-03-12',
    img: img40,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 41,
    name: 'Bluetooth Speaker',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 80,
    category: 'electronics',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 15,
    releaseDate: '2023-05-21',
    img: img41,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 42,
    name: 'Travel Backpack',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 60,
    category: 'outdoor',
    isFeatured: false,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 10,
    releaseDate: '2022-10-09',
    img: img42,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 43,
    name: 'Fitness Tracker',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 90,
    category: 'fitness',
    isFeatured: true,
    isNew: true,
    isDiscounted: false,
    isBestSeller: false,
    discountPercentage: 0,
    releaseDate: '2024-09-17',
    img: img43,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 44,
    name: 'Smart Thermostat',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 150,
    category: 'home',
    isFeatured: false,
    isNew: false,
    isDiscounted: true,
    isBestSeller: false,
    discountPercentage: 15,
    releaseDate: '2023-07-01',
    img: img44,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 45,
    name: 'Noise-Cancelling Headphones',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 250,
    category: 'electronics',
    isFeatured: true,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-02-18',
    img: img45,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 46,
    name: 'Digital Weighing Scale',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 50,
    category: 'fitness',
    isFeatured: false,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-05-08',
    img: img46,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 47,
    name: 'Gaming Chair',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 300,
    category: 'furniture',
    isFeatured: true,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 25,
    releaseDate: '2023-01-22',
    img: img47,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 48,
    name: 'Smart Light Bulb',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 20,
    category: 'home',
    isFeatured: true,
    isNew: true,
    isDiscounted: false,
    isBestSeller: false,
    discountPercentage: 0,
    releaseDate: '2024-10-01',
    img: img48,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 49,
    name: 'Electric Toothbrush',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium temporibus possimus sequi reiciendis. Maiores ipsum est qui assumenda voluptatibus illum corrupti sunt sit.',
    price: 100,
    category: 'personal care',
    isFeatured: false,
    isNew: false,
    isDiscounted: true,
    isBestSeller: true,
    discountPercentage: 10,
    releaseDate: '2023-08-18',
    img: img49,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
  {
    id: 50,
    name: 'Robot Vacuum Cleaner',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. In culpa possimus inventore laborum architecto recusandae est odio error maxime neque accusamus quos aut distinctio esse doloremque quo dolor alias unde molestiae, maiores, eum nam expedita. Explicabo culpa consequatur, reprehenderit dolorem praesentium.',
    price: 400,
    category: 'home',
    isFeatured: true,
    isNew: true,
    isDiscounted: false,
    isBestSeller: true,
    discountPercentage: 0,
    releaseDate: '2024-01-10',
    img: img50,
    noOfReviews: 0,
    noOfStarReview: 0,
    isWishList: false,
    qty: 1,
    isAvailable: true,
  },
];
